In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IPL.csv",encoding='latin1',low_memory=False)

In [3]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [4]:
df.tail()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
283673,283673,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,...,96,3,NaN,NaN,2,2,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283674,283674,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,1,...,97,3,NaN,NaN,2,3,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283675,283675,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,2,...,98,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283676,283676,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,...,98,3,NaN,NaN,6,4,0,"('MP Stoinis', 'P Simran Singh')",NaN,False
283677,283677,1529267,2026-04-16,T20,Indian Premier League,2,Punjab Kings,Mumbai Indians,16,3,...,99,3,NaN,NaN,10,5,0,"('MP Stoinis', 'P Simran Singh')",NaN,False

In [5]:
df.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
       'batting_partners', 'next_batter', 'striker_out'],
      dtype='str')

In [6]:
df['season'].unique()

<StringArray>
['2007/08',    '2009', '2009/10',    '2011',    '2012',    '2013',    '2014',
    '2015',    '2016',    '2017',    '2018',    '2019', '2020/21',    '2021',
    '2022',    '2023',    '2024',    '2025',    '2026']
Length: 19, dtype: str

In [7]:
df['season'] = df['season'].astype(str)

In [8]:
def fix_season(x):
    if x == '2007/08':
        return 2008
    elif x == '2009/10':
        return 2010
    elif x == '2020/21':
        return 2020
    else:
        return int(x)

df['season'] = df['season'].apply(fix_season)

In [9]:
sorted(df['season'].unique())

[np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025),
 np.int64(2026)]

In [10]:
df['season'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026])

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
columns_to_keep = [ 'match_id', 'date', 'match_type', 'event_name', 'innings',
                    'batting_team', 'bowling_team', 'over', 'ball','batter',
                    'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
                    'runs_extras', 'runs_total', 'runs_bowler', 'extra_type', 'non_striker', 'wicket_kind',
                    'player_out', 'runs_target', 'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
                    'toss_decision', 'venue', 'city','season','superover_winner', 'result_type', 'method',
                    'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
                    'team_runs', 'team_balls', 'team_wicket',]


columns_to_remove = ['Unnamed: 0','ball_no','runs_not_boundary','non_striker_pos','fielders', 'runs_target', 'review_batter',
                     'team_reviewed', 'review_decision', 'umpire', 'umpires_call','day', 'month', 'year','gender', 'team_type',
                      'balls_per_over', 'event_match_no', 'power_surge_start','batting_partners', 'next_batter', 'striker_out','new_batter',]

In [13]:
df.drop(columns=columns_to_remove,inplace=True)

In [14]:
df.columns

Index(['match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'batter', 'bat_pos',
       'runs_batter', 'balls_faced', 'bowler', 'valid_ball', 'runs_extras',
       'runs_total', 'runs_bowler', 'extra_type', 'non_striker', 'wicket_kind',
       'player_out', 'player_of_match', 'match_won_by', 'win_outcome',
       'toss_winner', 'toss_decision', 'venue', 'city', 'season',
       'superover_winner', 'result_type', 'method', 'overs', 'stage',
       'match_number', 'team_runs', 'team_balls', 'team_wicket', 'batter_runs',
       'batter_balls', 'bowler_wicket'],
      dtype='str')

In [15]:
df.shape

(283678, 42)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 42 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          283678 non-null  int64
 1   date              283678 non-null  str
 2   match_type        283678 non-null  str
 3   event_name        283678 non-null  str
 4   innings           283678 non-null  int64
 5   batting_team      283678 non-null  str
 6   bowling_team      283678 non-null  str
 7   over              283678 non-null  int64
 8   ball              283678 non-null  int64
 9   batter            283678 non-null  str
 10  bat_pos           283678 non-null  int64
 11  runs_batter       283678 non-null  int64
 12  balls_faced       283678 non-null  int64
 13  bowler            283678 non-null  str
 14  valid_ball        283678 non-null  int64
 15  runs_extras       283678 non-null  int64
 16  runs_total        283678 non-null  int64
 17  runs_bowler       283678 non-null  int64
 18  extra_type        15493 non-null   str
 19  non_striker       283678 non-null  str
 20  wicket_kind       14106 non-null   str
 21  player_out        14106 non-null   str
 22  player_of_match   283678 non-null  str
 23  match_won_by      283678 non-null  str
 24  win_outcome       278954 non-null  str
 25  toss_winner       283678 non-null  str
 26  toss_decision     283678 non-null  str
 27  venue             283678 non-null  str
 28  city              283678 non-null  str
 29  season            283678 non-null  int64
 30  superover_winner  3896 non-null    str
 31  result_type       4724 non-null    str
 32  method            3890 non-null    str
 33  overs             283678 non-null  int64
 34  stage             283678 non-null  str
 35  match_number      283678 non-null  str
 36  team_runs         283678 non-null  int64
 37  team_balls        283678 non-null  int64
 38  team_wicket       283678 non-null  int64
 39  batter_runs       283678 non-null  int64
 40  batter_balls      283678 non-null  int64
 41  bowler_wicket     283678 non-null  int64
dtypes: int64(19), str(23)
memory usage: 90.9 MB

In [17]:
df.isnull().sum()

match_id                 0
date                     0
match_type               0
event_name               0
innings                  0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bat_pos                  0
runs_batter              0
balls_faced              0
bowler                   0
valid_ball               0
runs_extras              0
runs_total               0
runs_bowler              0
extra_type          268185
non_striker              0
wicket_kind         269572
player_out          269572
player_of_match          0
match_won_by             0
win_outcome           4724
toss_winner              0
toss_decision            0
venue                    0
city                     0
season                   0
superover_winner    279782
result_type         278954
method              279788
overs                    0
stage                    0
match_number             0
team_runs                0
team_balls               0
team_wicket              0
batter_runs              0
batter_balls             0
bowler_wicket            0
dtype: int64

In [18]:
df['extra_type'] = df['extra_type'].fillna('No Extra')

df['wicket_kind'] = df['wicket_kind'].fillna('No Wicket')

df['player_out'] = df['player_out'].fillna('Not Out')

df['win_outcome'] = df['win_outcome'].fillna('No Result')

df['superover_winner'] = df['superover_winner'].fillna('No Super Over')

df['result_type'] = df['result_type'].fillna('Normal')

df['method'] = df['method'].fillna('Standard')

In [19]:
df.isnull().sum()

match_id            0
date                0
match_type          0
event_name          0
innings             0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bat_pos             0
runs_batter         0
balls_faced         0
bowler              0
valid_ball          0
runs_extras         0
runs_total          0
runs_bowler         0
extra_type          0
non_striker         0
wicket_kind         0
player_out          0
player_of_match     0
match_won_by        0
win_outcome         0
toss_winner         0
toss_decision       0
venue               0
city                0
season              0
superover_winner    0
result_type         0
method              0
overs               0
stage               0
match_number        0
team_runs           0
team_balls          0
team_wicket         0
batter_runs         0
batter_balls        0
bowler_wicket       0
dtype: int64

In [20]:
df['date'] = pd.to_datetime(df['date'])

In [21]:
df['date'].dt.year.unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026], dtype=int32)

In [22]:
df[df['date'] == 2026].shape

(0, 42)

In [23]:
df = df[df['date'].dt.year != 2026]

In [24]:
df['date'].dt.year.unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024, 2025], dtype=int32)

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 42 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          278205 non-null  int64
 1   date              278205 non-null  datetime64[us]
 2   match_type        278205 non-null  str
 3   event_name        278205 non-null  str
 4   innings           278205 non-null  int64
 5   batting_team      278205 non-null  str
 6   bowling_team      278205 non-null  str
 7   over              278205 non-null  int64
 8   ball              278205 non-null  int64
 9   batter            278205 non-null  str
 10  bat_pos           278205 non-null  int64
 11  runs_batter       278205 non-null  int64
 12  balls_faced       278205 non-null  int64
 13  bowler            278205 non-null  str
 14  valid_ball        278205 non-null  int64
 15  runs_extras       278205 non-null  int64
 16  runs_total        278205 non-null  int64
 17  runs_bowler       278205 non-null  int64
 18  extra_type        278205 non-null  str
 19  non_striker       278205 non-null  str
 20  wicket_kind       278205 non-null  str
 21  player_out        278205 non-null  str
 22  player_of_match   278205 non-null  str
 23  match_won_by      278205 non-null  str
 24  win_outcome       278205 non-null  str
 25  toss_winner       278205 non-null  str
 26  toss_decision     278205 non-null  str
 27  venue             278205 non-null  str
 28  city              278205 non-null  str
 29  season            278205 non-null  int64
 30  superover_winner  278205 non-null  str
 31  result_type       278205 non-null  str
 32  method            278205 non-null  str
 33  overs             278205 non-null  int64
 34  stage             278205 non-null  str
 35  match_number      278205 non-null  str
 36  team_runs         278205 non-null  int64
 37  team_balls        278205 non-null  int64
 38  team_wicket       278205 non-null  int64
 39  batter_runs       278205 non-null  int64
 40  batter_balls      278205 non-null  int64
 41  bowler_wicket     278205 non-null  int64
dtypes: datetime64[us](1), int64(19), str(22)
memory usage: 89.1 MB

In [26]:
df.dtypes

match_id                     int64
date                datetime64[us]
match_type                     str
event_name                     str
innings                      int64
batting_team                   str
bowling_team                   str
over                         int64
ball                         int64
batter                         str
bat_pos                      int64
runs_batter                  int64
balls_faced                  int64
bowler                         str
valid_ball                   int64
runs_extras                  int64
runs_total                   int64
runs_bowler                  int64
extra_type                     str
non_striker                    str
wicket_kind                    str
player_out                     str
player_of_match                str
match_won_by                   str
win_outcome                    str
toss_winner                    str
toss_decision                  str
venue                          str
city                           str
season                       int64
superover_winner               str
result_type                    str
method                         str
overs                        int64
stage                          str
match_number                   str
team_runs                    int64
team_balls                   int64
team_wicket                  int64
batter_runs                  int64
batter_balls                 int64
bowler_wicket                int64
dtype: object

In [27]:
numeric_cols = [
'runs_batter',
'runs_total',
'balls_faced',
'team_runs',
'team_wicket',
'over',
'ball'
]

df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)

In [28]:
df.describe()

,match_id,date,innings,over,ball,bat_pos,runs_batter,balls_faced,valid_ball,runs_extras,runs_total,runs_bowler,season,overs,team_runs,team_balls,team_wicket,batter_runs,batter_balls,bowler_wicket
count,2.782050e+05,278205,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.00000,278205.000000,278205.000000,278205.0,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000
mean,9.422687e+05,2017-01-23 17:45:07.831994,1.482914,9.193839,3.488855,3.612555,1.277378,0.967362,0.963182,0.067971,1.34535,1.320807,2016.710178,20.0,77.110498,58.614637,2.456972,18.327424,14.011211,0.045470
min,3.359820e+05,2008-04-18 00:00:00,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,2008.000000,20.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483530e+05,2012-05-05 00:00:00,1.000000,4.000000,2.000000,2.000000,0.000000,1.000000,1.000000,0.000000,0.00000,0.000000,2012.000000,20.0,36.000000,29.000000,1.000000,4.000000,5.000000,0.000000
50%,1.082601e+06,2017-04-13 00:00:00,1.000000,9.000000,3.000000,3.000000,1.000000,1.000000,1.000000,0.000000,1.00000,1.000000,2017.000000,20.0,73.000000,58.000000,2.000000,12.000000,11.000000,0.000000
75%,1.304049e+06,2022-03-27 00:00:00,2.000000,14.000000,5.000000,5.000000,1.000000,1.000000,1.000000,0.000000,1.00000,1.000000,2022.000000,20.0,113.000000,88.000000,4.000000,27.000000,20.000000,0.000000
max,1.485779e+06,2025-06-03 00:00:00,6.000000,19.000000,7.000000,11.000000,6.000000,1.000000,1.000000,7.000000,7.00000,7.000000,2025.000000,20.0,287.000000,121.000000,10.000000,175.000000,73.000000,1.000000
std,3.817198e+05,NaN,0.502571,5.681511,1.708263,2.168978,1.651107,0.177687,0.188315,0.343033,1.63762,1.642110,5.248572,0.0,49.957873,34.117619,2.100374,18.578093,11.833930,0.208333

In [29]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [30]:
df['batting_team'].unique()

<StringArray>
[      'Kolkata Knight Riders', 'Royal Challengers Bangalore',
         'Chennai Super Kings',             'Kings XI Punjab',
            'Rajasthan Royals',            'Delhi Daredevils',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [31]:
df['batting_team'] = df['batting_team'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
})

In [32]:
df['batting_team'].unique()

<StringArray>
[      'Kolkata Knight Riders', 'Royal Challengers Bengaluru',
         'Chennai Super Kings',                'Punjab Kings',
            'Rajasthan Royals',              'Delhi Capitals',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',      'Rising Pune Supergiant',
               'Gujarat Lions',        'Lucknow Super Giants',
              'Gujarat Titans']
Length: 15, dtype: str

In [33]:
df['bowling_team'].unique()

<StringArray>
['Royal Challengers Bangalore',       'Kolkata Knight Riders',
             'Kings XI Punjab',         'Chennai Super Kings',
            'Delhi Daredevils',            'Rajasthan Royals',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
              'Gujarat Titans',        'Lucknow Super Giants',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [34]:
df['bowling_team'] = df['bowling_team'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
})

In [35]:
df['bowling_team'].unique()

<StringArray>
['Royal Challengers Bengaluru',       'Kolkata Knight Riders',
                'Punjab Kings',         'Chennai Super Kings',
              'Delhi Capitals',            'Rajasthan Royals',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',      'Rising Pune Supergiant',
               'Gujarat Lions',              'Gujarat Titans',
        'Lucknow Super Giants']
Length: 15, dtype: str

In [36]:
df['season'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [37]:
df.reset_index(drop=True,inplace=True)

In [38]:
df.isnull().sum()

match_id            0
date                0
match_type          0
event_name          0
innings             0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bat_pos             0
runs_batter         0
balls_faced         0
bowler              0
valid_ball          0
runs_extras         0
runs_total          0
runs_bowler         0
extra_type          0
non_striker         0
wicket_kind         0
player_out          0
player_of_match     0
match_won_by        0
win_outcome         0
toss_winner         0
toss_decision       0
venue               0
city                0
season              0
superover_winner    0
result_type         0
method              0
overs               0
stage               0
match_number        0
team_runs           0
team_balls          0
team_wicket         0
batter_runs         0
batter_balls        0
bowler_wicket       0
dtype: int64

In [39]:
df.to_csv("final_cleaned_ipl_dataset.csv",index=False)

In [40]:
df['venue'].value_counts()

venue
Eden Gardens                                                               17988
Wankhede Stadium                                                           17591
M Chinnaswamy Stadium                                                      14907
Feroz Shah Kotla                                                           13950
Wankhede Stadium, Mumbai                                                   12547
MA Chidambaram Stadium, Chepauk                                            11760
Rajiv Gandhi International Stadium, Uppal                                  11604
Dubai International Cricket Stadium                                        11229
Sawai Mansingh Stadium                                                     11150
Punjab Cricket Association Stadium, Mohali                                  8266
MA Chidambaram Stadium, Chepauk, Chennai                                    8242
Narendra Modi Stadium, Ahmedabad                                            7923
Sheikh Zayed Stadium                                                        6925
Sharjah Cricket Stadium                                                     6672
Arun Jaitley Stadium, Delhi                                                 5687
Eden Gardens, Kolkata                                                       5448
Maharashtra Cricket Association Stadium                                     5294
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow       5235
Dr DY Patil Sports Academy, Mumbai                                          4905
M Chinnaswamy Stadium, Bengaluru                                            4549
Rajiv Gandhi International Stadium, Uppal, Hyderabad                        4451
Brabourne Stadium, Mumbai                                                   4057
Sawai Mansingh Stadium, Jaipur                                              4044
Dr DY Patil Sports Academy                                                  3993
Subrata Roy Sahara Stadium                                                  3825
Kingsmead                                                                   3643
Rajiv Gandhi International Stadium                                          3609
M.Chinnaswamy Stadium                                                       3494
Arun Jaitley Stadium                                                        3356
Maharashtra Cricket Association Stadium, Pune                               3120
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                         3037
Sardar Patel Stadium, Motera                                                2893
SuperSport Park                                                             2866
Punjab Cricket Association IS Bindra Stadium, Mohali                        2574
Brabourne Stadium                                                           2469
Punjab Cricket Association IS Bindra Stadium                                2429
Saurashtra Cricket Association Stadium                                      2381
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur          2313
Himachal Pradesh Cricket Association Stadium                                2159
MA Chidambaram Stadium                                                      2130
Holkar Cricket Stadium                                                      1965
New Wanderers Stadium                                                       1940
Zayed Cricket Stadium, Abu Dhabi                                            1874
Barabati Stadium                                                            1695
St George's Park                                                            1677
JSCA International Stadium Complex                                          1671
Newlands                                                                    1539
Shaheed Veer Narayan Singh International Stadium                            1431
Himachal Pradesh Cricket Association Stadium, Dharamsala                    1298
Barsapara Cricket Stadium, Guwahati                                         1223
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh            1207
Nehru Stadium                                                               1155
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam           963
Green Park                                                                   921
Vidarbha Cricket Association Stadium, Jamtha                                 742
De Beers Diamond Oval                                                        726
Buffalo Park                                                                 715
OUTsurance Oval                                                              500
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh      248
Name: count, dtype: int64

In [41]:
venue_mapping = {

    'Wankhede Stadium, Mumbai':'Wankhede Stadium',
    
    'Eden Gardens, Kolkata':'Eden Gardens',

    'M Chinnaswamy Stadium':'M Chinnaswamy Stadium',
    'M.Chinnaswamy Stadium':'M Chinnaswamy Stadium',
    'M Chinnaswamy Stadium, Bengaluru':'M Chinnaswamy Stadium',

    'MA Chidambaram Stadium, Chepauk':'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai':'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chennai':'MA Chidambaram Stadium',

    'Rajiv Gandhi International Stadium, Uppal':'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad':'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium':'Rajiv Gandhi International Stadium',

    'Arun Jaitley Stadium, Delhi':'Arun Jaitley Stadium',
    'Arun Jaitley Stadium':'Arun Jaitley Stadium',

    'Dr DY Patil Sports Academy, Mumbai':'Dr DY Patil Sports Academy',
    'Dr DY Patil Sports Academy':'Dr DY Patil Sports Academy',

    'Sawai Mansingh Stadium, Jaipur':'Sawai Mansingh Stadium',
    'Sawai Mansingh Stadium':'Sawai Mansingh Stadium',

    'Punjab Cricket Association Stadium, Mohali':'Punjab Cricket Association Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali':'Punjab Cricket Association Stadium',
    'Punjab Cricket Association IS Bindra Stadium':'Punjab Cricket Association Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh':'Punjab Cricket Association Stadium',

    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam':'ACA-VDCA Cricket Stadium',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium':'ACA-VDCA Cricket Stadium',

    'Maharashtra Cricket Association Stadium, Pune':'Maharashtra Cricket Association Stadium',

    'Brabourne Stadium, Mumbai':'Brabourne Stadium',

    'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow':'Ekana Cricket Stadium',

    'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh':'Maharaja Yadavindra Singh International Cricket Stadium',
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur':'Maharaja Yadavindra Singh International Cricket Stadium'
}

In [42]:
df['venue'] = df['venue'].replace(venue_mapping)

In [43]:
df['venue'].value_counts()

venue
Wankhede Stadium                                            30138
Eden Gardens                                                23436
M Chinnaswamy Stadium                                       22950
MA Chidambaram Stadium                                      22132
Rajiv Gandhi International Stadium                          19664
Sawai Mansingh Stadium                                      15194
Punjab Cricket Association Stadium                          14476
Feroz Shah Kotla                                            13950
Dubai International Cricket Stadium                         11229
Arun Jaitley Stadium                                         9043
Dr DY Patil Sports Academy                                   8898
Maharashtra Cricket Association Stadium                      8414
Narendra Modi Stadium, Ahmedabad                             7923
Sheikh Zayed Stadium                                         6925
Sharjah Cricket Stadium                                      6672
Brabourne Stadium                                            6526
Ekana Cricket Stadium                                        5235
ACA-VDCA Cricket Stadium                                     4000
Subrata Roy Sahara Stadium                                   3825
Kingsmead                                                    3643
Sardar Patel Stadium, Motera                                 2893
SuperSport Park                                              2866
Maharaja Yadavindra Singh International Cricket Stadium      2561
Saurashtra Cricket Association Stadium                       2381
Himachal Pradesh Cricket Association Stadium                 2159
Holkar Cricket Stadium                                       1965
New Wanderers Stadium                                        1940
Zayed Cricket Stadium, Abu Dhabi                             1874
Barabati Stadium                                             1695
St George's Park                                             1677
JSCA International Stadium Complex                           1671
Newlands                                                     1539
Shaheed Veer Narayan Singh International Stadium             1431
Himachal Pradesh Cricket Association Stadium, Dharamsala     1298
Barsapara Cricket Stadium, Guwahati                          1223
Nehru Stadium                                                1155
Green Park                                                    921
Vidarbha Cricket Association Stadium, Jamtha                  742
De Beers Diamond Oval                                         726
Buffalo Park                                                  715
OUTsurance Oval                                               500
Name: count, dtype: int64

In [44]:
def clean_venue(x):

    x = str(x)

    if 'Eden Gardens' in x:
        return 'Eden Gardens'

    elif 'Wankhede' in x:
        return 'Wankhede Stadium'

    elif 'Chinnaswamy' in x:
        return 'M Chinnaswamy Stadium'

    elif 'Chidambaram' in x:
        return 'MA Chidambaram Stadium'

    elif 'Rajiv Gandhi International' in x:
        return 'Rajiv Gandhi International Stadium'

    elif 'Arun Jaitley' in x or 'Feroz Shah Kotla' in x:
        return 'Arun Jaitley Stadium'

    elif 'Sawai Mansingh' in x:
        return 'Sawai Mansingh Stadium'

    elif 'Punjab Cricket Association' in x:
        return 'Punjab Cricket Association Stadium'

    elif 'Dr DY Patil' in x or 'DY Patil' in x:
        return 'Dr DY Patil Sports Academy'

    elif 'Maharashtra Cricket Association' in x:
        return 'Maharashtra Cricket Association Stadium'

    elif 'Dr. Y.S. Rajasekhara Reddy' in x:
        return 'ACA-VDCA Cricket Stadium'

    elif 'Brabourne' in x:
        return 'Brabourne Stadium'

    elif 'Narendra Modi' in x or 'Sardar Patel' in x:
        return 'Narendra Modi Stadium'

    elif 'Ekana' in x or 'Bharat Ratna' in x:
        return 'Ekana Cricket Stadium'

    elif 'Maharaja Yadavindra' in x:
        return 'Maharaja Yadavindra Singh International Cricket Stadium'

    elif 'Himachal Pradesh Cricket Association' in x or 'Dharamsala' in x:
        return 'Himachal Pradesh Cricket Association Stadium'

    elif 'Sheikh Zayed' in x or 'Zayed Cricket Stadium' in x:
        return 'Sheikh Zayed Stadium'

    else:
        return x

In [45]:
df['venue'] = df['venue'].apply(clean_venue)

In [46]:
df['venue'].value_counts()

venue
Wankhede Stadium                                           30138
Eden Gardens                                               23436
Arun Jaitley Stadium                                       22993
M Chinnaswamy Stadium                                      22950
MA Chidambaram Stadium                                     22132
Rajiv Gandhi International Stadium                         19664
Sawai Mansingh Stadium                                     15194
Punjab Cricket Association Stadium                         14476
Dubai International Cricket Stadium                        11229
Narendra Modi Stadium                                      10816
Dr DY Patil Sports Academy                                  8898
Sheikh Zayed Stadium                                        8799
Maharashtra Cricket Association Stadium                     8414
Sharjah Cricket Stadium                                     6672
Brabourne Stadium                                           6526
Ekana Cricket Stadium                                       5235
ACA-VDCA Cricket Stadium                                    4000
Subrata Roy Sahara Stadium                                  3825
Kingsmead                                                   3643
Himachal Pradesh Cricket Association Stadium                3457
SuperSport Park                                             2866
Maharaja Yadavindra Singh International Cricket Stadium     2561
Saurashtra Cricket Association Stadium                      2381
Holkar Cricket Stadium                                      1965
New Wanderers Stadium                                       1940
Barabati Stadium                                            1695
St George's Park                                            1677
JSCA International Stadium Complex                          1671
Newlands                                                    1539
Shaheed Veer Narayan Singh International Stadium            1431
Barsapara Cricket Stadium, Guwahati                         1223
Nehru Stadium                                               1155
Green Park                                                   921
Vidarbha Cricket Association Stadium, Jamtha                 742
De Beers Diamond Oval                                        726
Buffalo Park                                                 715
OUTsurance Oval                                              500
Name: count, dtype: int64

In [47]:
pom_df = df.drop_duplicates(subset=['match_id'])

In [48]:
pom_count = pom_df['player_of_match'].value_counts()

In [49]:
pom_count.head(10)

player_of_match
AB de Villiers    25
CH Gayle          22
RG Sharma         21
V Kohli           19
MS Dhoni          18
DA Warner         18
SP Narine         17
SR Watson         16
YK Pathan         16
RA Jadeja         16
Name: count, dtype: int64

In [50]:
df.to_csv("final_cleaned_ipl_dataset.csv", index=False)

In [51]:
df.to_excel("final_cleaned_ipl_dataset.xlsx",index=False)